### ISSUE TITLE
Application crash while capture image and back to screen.

### ISSUE THREAD

**Issue by daxeshvekariya** [akshay2211/PixImagePicker#1]
API Level : 22
Device : google nexus 5

05-16 01:17:29.400 9041-9067/com.fxn.instapickersample E/AndroidRuntime: FATAL EXCEPTION: CameraViewWorker
                                                                         Process: com.fxn.instapickersample, PID: 9041
                                                                         java.lang.IllegalArgumentException: Unknown pattern character 'Y'
                                                                             at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
                                                                             at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:289)
                                                                             at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)
                                                                             at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:249)
                                                                             at com.fxn.utility.Utility.writeImage(Utility.java:240)
                                                                             at com.fxn.pix.Pix$8$1.callback(Pix.java:409)
                                                                             at com.fxn.pix.Pix$8$1.callback(Pix.java:405)
                                                                             at com.wonderkiln.camerakit.CameraView$5.imageCaptured(CameraView.java:440)
                                                                             at com.wonderkiln.camerakit.Camera1$2.onPictureTaken(Camera1.java:288)
                                                                             at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1094)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by akshay2211** [comment]
Hello @daxeshvekariya , Thankyou for trying **PIX** ,
the bug you reported is been solved 
please use the latest version **1.0.3**
Thanks.
