### ISSUE TITLE
Android Version 10 Issue

### ISSUE THREAD

**Issue by DevAlpesh** [akshay2211/PixImagePicker#103]
Image is not loading from selected path in Android Version 10.

**Comment by roelandwyns** [comment]
Yes indeed, not working on OnePlus 7t with android 10 here...

**Comment by Uvneshkumar** [comment]
use android:requestLegacyExternalStorage="true" inside application tag in manifest untill the dev fixes it.

source:
https://stackoverflow.com/a/58761220
https://stackoverflow.com/a/56821320

**Comment by adatapoint** [comment]
Thank you! It works like a charm!

**Comment by adatapoint** [comment]
> use android:requestLegacyExternalStorage="true" inside application tag in manifest untill the dev fixes it.
> 
> source:
> https://stackoverflow.com/a/58761220
> https://stackoverflow.com/a/56821320

Thank you! It works like a charm!

**Comment by Skolagetechnologies** [comment]
> use android:requestLegacyExternalStorage="true" inside application tag in manifest untill the dev fixes it.
> 
> source:
> https://stackoverflow.com/a/58761220
> https://stackoverflow.com/a/56821320

Thanks, dude for this.

**Comment by jetsekoopmans** [comment]
Any updates on this?

**Comment by marcauberer** [comment]
Did you add android:requestLegacyExternalStorage="true"?

**Comment by jetsekoopmans** [comment]
I did, and that works! 👍 

@Uvneshkumar mentioned "untill the dev fixes it.", I thought maybe they fixed it already?

**Comment by marcauberer** [comment]
Seems like this was fixed in one of the latest commits by @akshay2211

**Comment by LebonNic** [comment]
Hi guys!

I can't run the PixImagePicker library anymore on an emulator. I use a Pixel 2 API R and I get an error even with the option android:requestLegacyExternalStorage="true" in the app manifest. Here is the stack trace:

```
Caused by: java.lang.IllegalArgumentException: Volume external_primary not found
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at android.content.ContentResolver.query(ContentResolver.java:1115)
        at android.content.ContentResolver.query(ContentResolver.java:1071)
        at com.fxn.utility.Utility.getImageVideoCursor(Utility.java:169)
        at com.fxn.pix.Pix.updateImages(Pix.java:741)
        at com.fxn.pix.Pix.initialize(Pix.java:591)
        at com.fxn.pix.Pix.onCreate(Pix.java:369)
        at android.app.Activity.performCreate(Activity.java:7989)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7478) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 
```

I think it is related to the topic of this issue, because I don't have the problem on older versions of Android.

Best regards,
Nicolas

**Comment by LebonNic** [comment]
Ok I solve the issue by wiping data in the AVD Manager... Sorry for the inconvenience.
