### ISSUE TITLE
ArrayIndexOutOfBoundsException in MainImageAdapter on getSectionMonthYearText

### ISSUE THREAD

**Issue by 73k05** [akshay2211/PixImagePicker#104]
Hi,

thank you @akshay2211 for the work you have been doing here :-)

I've got a new crash from the community.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.fxn.adapters.MainImageAdapter.getSectionMonthYearText(MainImageAdapter.java:162)
       at com.fxn.pix.Pix.setRecyclerViewPosition(Pix.java:799)
       at com.fxn.pix.Pix.onTouch(Pix.java:880)
       at android.view.View.dispatchTouchEvent(View.java:13949)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4012)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
       at android.view.View.dispatchPointerEvent(View.java:14212)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7675)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7644)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7605)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I think you can solve it with similar fix as #79 !

Cheers
@73k05

**Comment by 73k05** [comment]
Fixed here https://github.com/73k05/PixImagePicker/commit/0726455463264a3b157a7d035c407a9580d4f8d7

**Comment by akshay2211** [comment]
thanks @73k05, really appreciate your help
its been fixed, just as you suggested.
it will be live in next release.
