### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Can't take hq pictures while in VIDEO mode

### ISSUE THREAD

**Issue by iosandroiddev** [akshay2211/PixImagePicker#124]
Getting the following exception in Pixel 2 XL while Capturing a video:

```
Fatal Exception: java.lang.IllegalStateException: Can't take hq pictures while in VIDEO mode
       at com.otaliastudios.cameraview.engine.CameraBaseEngine$3.run(CameraBaseEngine.java:503)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$3.run(CameraStateOrchestrator.java:100)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:75)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:72)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by 73k05** [comment]
I reproduced this, it is when you record a video and you click 2/3 times quickly after as if you would like to take pictures.
