### ISSUE TITLE
not open camera

### ISSUE THREAD

**Issue by dverdugo85** [akshay2211/PixImagePicker#129]
I have this issue:

java.lang.IllegalStateException: This value is not sanitized: -552160
at com.otaliastudios.cameraview.engine.offset.Angles.sanitizeInput(Angles.java:128)
at com.otaliastudios.cameraview.engine.offset.Angles.setSensorOffset(Angles.java:41)
at com.otaliastudios.cameraview.engine.Camera1Engine.collectCameraInfo(Camera1Engine.java:140)
at com.otaliastudios.cameraview.engine.CameraEngine$5.call(CameraEngine.java:386)
at com.otaliastudios.cameraview.engine.CameraEngine$5.call(CameraEngine.java:383)
at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:69)
at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:60)
at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.os.HandlerThread.run(HandlerThread.java:67)

```
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:keepScreenOn = "true"
        android:layout_gravity="center"
        app:cameraFacing = "back"
        app:cameraFlash = "off"
        app:cameraGestureLongTap = "autoFocus"
        app:cameraGesturePinch = "zoom"
        app:cameraGestureTap = "autoFocus"
        app:cameraPictureFormat = "jpeg"
        app:cameraVideoCodec = "deviceDefault"
        app:cameraWhiteBalance = "auto"
        />
```

**Comment by akshay2211** [comment]
Hi @dverdugo85,
This issue is because of otaliastudios.cameraview library that pix is using.
I am planing to migrate to androix camera library in the next release.
