### ISSUE TITLE
App crashes on API level 29 when using camera 

### ISSUE THREAD

**Issue by dasBikash84** [akshay2211/PixImagePicker#159]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at com.fxn.pix.Pix$8$1.onFileReady(Pix.java:456)
        at com.otaliastudios.cameraview.CameraUtils$1$1.run(CameraUtils.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by anandarpit** [comment]
+1 
I get the same error!!
And I thought maybe my code was wrong 😅

**Comment by akshaaatt** [comment]
For now add  android:requestLegacyExternalStorage="true" to the manifest to tackle this but it won't work once you set the target to API Level 30

**Comment by iadcialim** [comment]
Yeah for now. I set my targetSDKVersion to 29 and it works

**Comment by akshay2211** [comment]
Hello @anandarpit 
This issue is been resolved in the latest release  [PixImagePicker Version 1.5.5](https://github.com/akshay2211/PixImagePicker#download)
