### ISSUE TITLE
Taking a picture on Android 9 & 10: crash report

### ISSUE THREAD

**Issue by JobGetabu** [akshay2211/PixImagePicker#170]
Brand: OPPO
Model: A1k
Orientation: Portrait

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
       at com.fxn.pix.Pix$8$1.onFileReady(Pix.java:456)
       at com.otaliastudios.cameraview.CameraUtils$1$1.run(CameraUtils.java:124)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by rameshmobileapp** [comment]
Add this line into your manifest file to avoid the crash  android:requestLegacyExternalStorage="true", It is working for me......
