### ISSUE TITLE
Camera is not working in android version 11

### ISSUE THREAD

**Issue by SUKRALIYA** [akshay2211/PixImagePicker#171]
Hi,
 Camera is not working in android version 11 only . how to resolve this issue. In onFileReady method File is showing null

result.toFile(photo, new FileCallback() {
                    @Override
                    public void onFileReady(@Nullable File photo) {
                        Utility.vibe(Pix.this, 50);
                        assert photo != null;
                        Img img = new Img("", "", photo.getAbsolutePath(), "", 1);
                        selectionList.add(img);
                        Utility.scanPhoto(Pix.this, photo);
                        returnObjects();
                    }
                });

**Comment by jeanraymonddaher** [comment]
you should add your device to help and maybe logs, as I run on android 11 fine

**Comment by SUKRALIYA** [comment]
One Plus android  device .
Logs details.

2021-04-05 12:14:55.012 28306-28306/com.app.udbara E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted


Manifest.--
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <application
        android:icon="@drawable/app_icon"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:requestLegacyExternalStorage="true"
        android:roundIcon="@drawable/app_icon"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true"
        tools:targetApi="m">

**Comment by SUKRALIYA** [comment]
2021-04-05 12:32:39.513 11610-11610/com.app.udbara E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2021-04-05 12:32:55.598 11610-11610/com.app.udbara E/SensorManager: registerListenerImpl sensorName:lsm6dsm Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.app.udbara,callingPid:11610,callingUid:10413
2021-04-05 12:33:09.359 11610-11610/com.app.udbara E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.udbara, PID: 11610
    java.lang.AssertionError
        at com.fxn.pix.Pix$8$1.onFileReady(Pix.java:469)
        at com.otaliastudios.cameraview.CameraUtils$1$1.run(CameraUtils.java:124)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
