### ISSUE TITLE
targetSDKversion : 30 , running on Android 10 gives crash with accesing storage

### ISSUE THREAD

**Issue by siva-komaragiri** [akshay2211/PixImagePicker#178]
Using Pix 1.5.6
Getting exception caused by "Permission denied" when running app with targetSDKversion 30 on android 10. 

Proposed solution: onPictureTaken > dir = getExternalFilesDir(options.getPath()) , irrespective of Build.VERSION

E/CameraUtils: writeToFile: could not write file. java.io.FileNotFoundException: /storage/emulated/0/Pix/Camera/IMG_20210419_112476.jpg: open failed: EACCES (Permission denied)
    java.io.FileNotFoundException: /storage/emulated/0/Pix/Camera/IMG_20210419_112476.jpg: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at com.otaliastudios.cameraview.CameraUtils.writeToFile(CameraUtils.java:92)
        at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:121)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)

**Comment by hugomc92** [comment]
Put this in your AndroidManifest.xml and it'll work

`android:requestLegacyExternalStorage="true"
android:preserveLegacyExternalStorage="true"`

**Comment by akshay2211** [comment]
Kindly refer to new version of PixImagePicker
Thanks
