### ISSUE TITLE
Returning Null when no image selected

### ISSUE THREAD

**Issue by biswanathd** [akshay2211/PixImagePicker#18]
06-20 18:32:58.860 32603-32603/{app package} E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aquatech.petdetective, PID: 32603
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=0, data=null} to activity {{app package}/{app package}.activities.add_edit_pet.AddEditPetActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4220)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4263)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at {app package}.activities.add_edit_pet.AddEditPetActivity.onActivityResult(AddEditPetActivity.kt)
        at android.app.Activity.dispatchActivityResult(Activity.java:7025)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4216)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4263) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6349) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by akshay2211** [comment]
Hello @biswanathd ,
Are you facing this in only a particular scenario or every time?
I am not able to generate this error can you kindly share a bit more info.

**Comment by BarmanInfo** [comment]
Same problem facing while no Image Selected. Getting null while returning from camera view without selecting any image. 

Device : Samsung Device Galaxy On5 Pro or Any Samsung Device
Os Version: 7.1.1
