### ISSUE TITLE
Same issue pls fix

### ISSUE THREAD

**Issue by LEGEND007ALWAYS** [akshay2211/PixImagePicker#181]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:764)

**Comment by LEGEND007ALWAYS** [comment]
Pls close this issue
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:764)
