### ISSUE TITLE
IllegalStateException PixFragment not attached to an activity while rotating quickly

### ISSUE THREAD

**Issue by 73k05** [akshay2211/PixImagePicker#192]
- Prerequisite: might need to apply workaround explained in #191  otherwise the crash is different than the one that follows
- Reproduce: 
  - open the SampleApp
  - click `Fragment Implementation Sample`
  - click the add photo camera button (bottom right)
  - Rotate many times quickly
- Possible resolving: Try/catch on PixFragment:72 line Anyway if the bar is hidden the first time it will not show again after a rotate.

```java.lang.IllegalStateException: Fragment PixFragment{83405f4} (d8fd8d31-47d3-4d95-871a-eb483fac2401) not attached to an activity.
        at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
        at io.ak1.pix.PixFragment.onResume$lambda-3(PixFragment.kt:72)
        at io.ak1.pix.PixFragment.lambda$_Sc77N0_JONaZIh5f07IIkNDKxM(Unknown Source:0)
        at io.ak1.pix.-$$Lambda$PixFragment$_Sc77N0_JONaZIh5f07IIkNDKxM.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

Here is the code that crashes:
```    override fun onResume() {
        super.onResume()
        if (mBottomSheetBehavior?.state == BottomSheetBehavior.STATE_COLLAPSED) {
            Handler(Looper.getMainLooper()).postDelayed({
                requireActivity().hideStatusBar()
            }, 200)

        }
    }
```

**Comment by akshay2211** [comment]
Thanks, Olivier for the PR
