### ISSUE TITLE
Crashes on Nexus 5 and does not pick multiple images.

### ISSUE THREAD

**Issue by omegareloaded** [akshay2211/PixImagePicker#20]
Crashes on Nexus 5X.

FATAL EXCEPTION: CameraViewWorker
                                                               
                                                                 java.lang.RuntimeException: startPreview failed
                                                                     at android.hardware.Camera.startPreview(Native Method)
                                                                     at com.wonderkiln.camerakit.Camera1.start(Camera1.java:128)
                                                                     at com.wonderkiln.camerakit.CameraView$2.run(CameraView.java:266)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)

**Comment by akshay2211** [comment]
Hello @omegareloaded ,
it is a camerakit library issue please check issue  [#158](https://github.com/CameraKit/camerakit-android/issues/158)
it will be fixed here when this issue is resolved in camerakit.
