### ISSUE TITLE
on api 30 crash after selecting image

### ISSUE THREAD

**Issue by SMDPLAYER** [akshay2211/PixImagePicker#200]
E/CameraEngine: onStopBind Could not release surface java.io.IOException: setPreviewTexture failed
    java.io.IOException: setPreviewTexture failed
        at android.hardware.Camera.setPreviewTexture(Native Method)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onStopBind(Camera1Engine.java:318)
        at com.otaliastudios.cameraview.engine.CameraEngine$9.call(CameraEngine.java:487)
        at com.otaliastudios.cameraview.engine.CameraEngine$9.call(CameraEngine.java:484)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:69)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:60)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$3.run(CameraOrchestrator.java:152)
        at com.otaliastudios.cameraview.internal.WorkerHandler.run(WorkerHandler.java:137)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.execute(CameraOrchestrator.java:147)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.access$100(CameraOrchestrator.java:34)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.run(CameraOrchestrator.java:137)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraEngine: EXCEPTION: Got CameraException. Dispatching to callback.

**Comment by SMDPLAYER** [comment]
> I have the same issue, which version are you using, please? @SMDPLAYER

1.5.6 @LobnaMazhar
