### ISSUE TITLE
NullPointerException on getRealMetrics in CameraXManager.bindCameraUseCases

### ISSUE THREAD

**Issue by 73k05** [akshay2211/PixImagePicker#204]
Hi,

I've got this crash from my community:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getRealMetrics(android.util.DisplayMetrics)' on a null object reference
       at io.ak1.pix.helpers.CameraXManager.bindCameraUseCases(CameraXManager.java:62)
       at io.ak1.pix.helpers.CameraXManager.setUpCamera$lambda-0(CameraXManager.java:55)
       at io.ak1.pix.helpers.CameraXManager.lambda$saIgVXdcX8hBqOG6Idaj-FlC7bY(CameraXManager.java)
       at io.ak1.pix.helpers.-$$Lambda$CameraXManager$saIgVXdcX8hBqOG6Idaj-FlC7bY.run(-.java:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

This PR #203 might do the trick, let me know if that is good for merging ✅ 

Bests

**Comment by akshay2211** [comment]
Thanks, @73k05 for the PR 
#203 is now merged.

**Comment by iadcialim** [comment]
@akshay2211 which version has this change?
