### ISSUE TITLE
Cash issue

### ISSUE THREAD

**Issue by pmrzygweb** [akshay2211/PixImagePicker#215]
2021-10-19 15:19:30.454 26719-26719/com.imessageforandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imessageforandroid, PID: 26719
    android.view.InflateException: Binary XML file line #22: Binary XML file line #13: Error inflating class com.google.android.material.card.MaterialCardView
    Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.google.android.material.card.MaterialCardView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.createCustomViewInternal(-ViewPumpLayoutInflater.kt:220)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$createCustomViewInternal(-ViewPumpLayoutInflater.kt:19)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:421)
        at com.lokalise.sdk.LokalisePreInterceptor.inflateView(LokaliseInterceptor.kt:144)
        at com.lokalise.sdk.LokalisePreInterceptor.intercept(LokaliseInterceptor.kt:71)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
        at com.lokalise.sdk.LokalisePostInterceptor.intercept(LokaliseInterceptor.kt:50)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
        at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:399)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:963)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
        at io.ak1.pix.databinding.FragmentPixBinding.inflate(FragmentPixBinding.java:57)
        at io.ak1.pix.PixFragment.onCreateView(PixFragment.kt:101)
        at io.ak1.pix.PixFragment.onCreateView(PixFragment.kt:40)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
2021-10-19 15:19:30.454 26719-26719/com.imessageforandroid E/AndroidRuntime:     at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:124)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:114)
        	... 41 more

Do you have any idea what went wrong?

**Comment by akshay2211** [comment]
Hie @pmrzygweb 
Please create [permissions_layout](https://github.com/akshay2211/PixImagePicker/blob/master/pix/src/main/res/layout/permissions_layout.xml) with the same ids, but with supported components according to your theme. 
it will override the permissions_layout in lib.
PS: Apologies for the delay in response

**Comment by UmairAhmed85** [comment]
> Hie @pmrzygweb Please create [permissions_layout](https://github.com/akshay2211/PixImagePicker/blob/master/pix/src/main/res/layout/permissions_layout.xml) in your layout folder with the same ids, but with supported components according to your theme. it will override the permissions_layout in lib. PS: Apologies for the delay in response

Making same layout inside our local layout folder doesn't work. It still picks up the binding with in your library and crash if we are not using MaterialTheme
It would be great if library could skip permissions in cases camera permissions are already granted. And if we can extend the PixFragment.
Currently, i cannot find a way to avoid this crash unless I used MaterialTheme which is not an options at the moment.
