### ISSUE TITLE
While Camera opened, show black screen on some devices

### ISSUE THREAD

**Issue by amantheshooter** [akshay2211/PixImagePicker#242]

**Comment by vkfan** [comment]
I got this same issue in one of my project and fixed it by setting a small delay before adding pix fragment. Like this;

   Handler(Looper.getMainLooper()).postDelayed(Runnable {
                showCameraFragment()
            }, 100)

**Comment by luzlaura98** [comment]
I has the same problem, At first It's working on my device. After testing, sometimes camera es not working and screen keeps in black. Switching frontal mode, sometimes camera is available again. 

```
E/CameraXBasic: Use case binding failed
    java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 1.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.impl.VideoCaptureConfig@f2947e9, androidx.camera.core.impl.ImageCaptureConfig@224e870, androidx.camera.core.impl.PreviewConfig@f562ab3]
        at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:278)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:459)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:288)
        at io.ak1.pix.helpers.CameraXManager.bindCameraUseCases(CameraXManager.kt:169)
        at io.ak1.pix.helpers.ControlsHelperKt.setupClickControls$lambda-11(ControlsHelper.kt:242)
        at io.ak1.pix.helpers.ControlsHelperKt.lambda$WsTRcNk_GL-aVNUGEElp2w7Zqv8(Unknown Source:0)
        at io.ak1.pix.helpers.-$$Lambda$ControlsHelperKt$WsTRcNk_GL-aVNUGEElp2w7Zqv8.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```
