### ISSUE TITLE
PixFragment.kt line 261

### ISSUE THREAD

**Issue by shivam21** [akshay2211/PixImagePicker#245]
Saw few crashes on firebase

**Able to Reproduce:** No
**Device Details on which crash occurred:**
Brand:samsung
Model:Galaxy A10
Orientation: Portrait
RAM free: 563.38 MB
Disk free: 3.49 GB

Stacktrace:
Fatal Exception: java.lang.IllegalStateException: Fragment PixFragment{b7e4184} (a8406dfe-a5b2-4c2e-868d-12137c3b0452) not attached to an activity.
       at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
       at io.ak1.pix.PixFragment$setupControls$1.invoke(PixFragment.kt:261)
       at io.ak1.pix.PixFragment$setupControls$1.invoke(PixFragment.kt:256)
       at io.ak1.pix.helpers.ControlsHelperKt$setupClickControls$1$1$1.invoke(ControlsHelper.kt:100)
       at io.ak1.pix.helpers.ControlsHelperKt$setupClickControls$1$1$1.invoke(ControlsHelper.kt:97)
       at io.ak1.pix.helpers.CameraXManager$takePhoto$1.onImageSaved(CameraXManager.kt:307)
       at androidx.camera.core.ImageCapture$2.onImageSaved(ImageCapture.java:917)
       at androidx.camera.core.ImageSaver.lambda$postSuccess$1(ImageSaver.java:329)
       at androidx.camera.core.ImageSaver.lambda$postSuccess$1$ImageSaver(ImageSaver.java)
       at androidx.camera.core.-$$Lambda$ImageSaver$29vxg6qyjKwPRXgWrIwgYVInWKE.run(lambda:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by The-Vishalist** [comment]
The same crash happened to me.
```
Fatal Exception: java.lang.IllegalStateException: Fragment i{cc2f7a8} (ee9ca5da-7f1e-4a5c-9dc4-f426bf5412e1) not attached to an activity.
       at androidx.fragment.app.Fragment.requireActivity(Fragment.java:947)
       at io.ak1.pix.PixFragment$setupControls$1.invoke(PixFragment.kt:261)
       at io.ak1.pix.PixFragment$setupControls$1.invoke(PixFragment.kt:256)
       at io.ak1.pix.helpers.ControlsHelperKt$setupClickControls$1$1$1.invoke(ControlsHelper.kt:100)
       at io.ak1.pix.helpers.ControlsHelperKt$setupClickControls$1$1$1.invoke(ControlsHelper.kt:97)
       at io.ak1.pix.helpers.CameraXManager$takePhoto$1.onImageSaved(CameraXManager.kt:307)
       at androidx.camera.core.ImageCapture$2.onImageSaved(ImageCapture.java:844)
       at androidx.camera.core.ImageSaver.lambda$postSuccess$1(ImageSaver.java:308)
       at androidx.camera.core.ImageSaver.$r8$lambda$29vxg6qyjKwPRXgWrIwgYVInWKE(ImageSaver.java)
       at androidx.camera.core.ImageSaver$$InternalSyntheticLambda$6$dbf6dfa65371b7d1b80adf21157bd9ad950051587131888dfb6e0dcab05db99f$0.run(ImageSaver.java:4)
       at android.os.Handler.handleCallback(Handler.java:978)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```
Device Brand: Motorola
Model: moto g52
Orientation: Portrait
RAM free: 1.32 GB
Disk free: 84.69 GB
Version: Android 12
Orientation: Portrait
Rooted: No
occurred in other devices as well, 5 crash events affecting 3 users.  @akshay2211
