### ISSUE TITLE
PixImagePicker crashes if the app theme is not inherited from Theme.MaterialComponents

### ISSUE THREAD

**Issue by or-else** [akshay2211/PixImagePicker#263]
**Describe the bug**
PixImagePicker does not work if the app theme is not inherited from `Theme.MaterialComponents`.

**To Reproduce**
Have the app theme be anything but inherited from MaterialComponents, launch PixImagePicker and observe the crash while inflating `layout/permissions_layout`:

```
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:216)
at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:144)
at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:170)
at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:160)
at java.lang.reflect.Constructor.newInstance0(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
at android.view.LayoutInflater.createView(LayoutInflater.java:858) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) 
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1235) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:686) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:538) 
at io.ak1.pix.databinding.FragmentPixBinding.inflate(FragmentPixBinding.java:57) 
at io.ak1.pix.PixFragment.onCreateView(PixFragment.kt:105) 
at io.ak1.pix.PixFragment.onCreateView(PixFragment.kt:41) 
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104) 
```

**Expected behavior**
I expect the library to have no hardcoded dependencies on particular themes.

I believe this is the same as #215

**Comment by or-else** [comment]
Regarding advise:

> Please create [permissions_layout](https://github.com/akshay2211/PixImagePicker/blob/master/pix/src/main/res/layout/permissions_layout.xml) in your layout folder with the same ids, but with supported components according to your theme. 
it will override the permissions_layout in lib.

I understand I can create a fork and fix it myself, but it would be nice to fix the actual problem in the library.
