### ISSUE TITLE
Application crash on getSupportActionBar().hide()

### ISSUE THREAD

**Issue by DaatSer** [akshay2211/PixImagePicker#3]
```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fxn.pix.Pix}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.hide()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.hide()' on a null object reference
                      at com.fxn.pix.Pix.initialize(Pix.java:333)
                      at com.fxn.pix.Pix.onCreate(Pix.java:316)
                      at android.app.Activity.performCreate(Activity.java:6999)
                      at android.app.Activity.performCreate(Activity.java:6990)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6494) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by akshay2211** [comment]
Hello @DaatSer , can u share more info about from where you are calling it or the style you have implemented, will it be possible for you to share the code.

**Comment by EsmaeilMohamed** [comment]
same issue happened with me

**Comment by DaatSer** [comment]
Hi @akshay2211 , I'm using NoActionBar style. But in some activities i have defined toolbars and set them as supportActionBar, maybe if you try to check for null before hide() method it will solve problem.

**Comment by akshay2211** [comment]
@DaatSer @EsmaeilMohamed Bug fixed 
Please use the latest version **1.0.2**
