### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by kostasoft** [akshay2211/PixImagePicker#45]
Hello!

phone: Galaxy S
android: 4.4.2

The following error occurs during initialization.
Apparently, the Utility.getCursor (Pix.this) method returns an empty value.

```
Caused by java.lang.NullPointerException
       at com.fxn.pix.Pix.updateImages(Pix.java:594)
       at com.fxn.pix.Pix.initialize(Pix.java:585)
       at com.fxn.pix.Pix.onCreate(Pix.java:325)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
       at android.app.ActivityThread.access$800(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5081)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by akshay2211** [comment]
Hello @kostasoft 
this is resolved in the latest version.
