### ISSUE TITLE
crash with kotlin coroutines

### ISSUE THREAD

**Issue by vkhadir** [akshay2211/PixImagePicker#64]
hello i have this crash whenever i try to start the imagepicker and apperntly is a probleme that has been fixed by fotapparat in the version 2.6.1 but the pix 1.2.5 version uses the 2.3.1

https://github.com/RedApparat/Fotoapparat/issues/314

```
2019-02-07 17:20:32.946 28475-28475/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.geev.application.stage, PID: 28475
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/CompletableDeferredKt;
        at io.fotoapparat.hardware.CameraDevice.<init>(CameraDevice.kt:48)
        at io.fotoapparat.hardware.Device.<init>(Device.kt:39)
        at io.fotoapparat.hardware.Device.<init>(Device.kt:34)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48)
        at io.fotoapparat.FotoapparatBuilder.buildInternal(FotoapparatBuilder.kt:190)
        at io.fotoapparat.FotoapparatBuilder.build(FotoapparatBuilder.kt:179)
        at com.fxn.pix.Pix.initialize(Pix.java:373)
        at com.fxn.pix.Pix.onCreate(Pix.java:325)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2896)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.experimental.CompletableDeferredKt" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/fr.geev.application.stage-6HPvTyE1B-ID2YGg3dlnZw==/base.apk", zip file "/data/app/fr.geev.application.stage-6HPvTyE1B-ID2YGg3dlnZw==/split_lib_resources_apk.apk", zip file "/data/app/fr.geev.application.stage-6HPvTyE1B-ID2YGg3dlnZw==/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/fr.geev.application.stage-6HPvTyE1B-ID2YGg3dlnZw==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.fotoapparat.hardware.CameraDevice.<init>(CameraDevice.kt:48) 
        at io.fotoapparat.hardware.Device.<init>(Device.kt:39) 
        at io.fotoapparat.hardware.Device.<init>(Device.kt:34) 
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55) 
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48) 
        at io.fotoapparat.FotoapparatBuilder.buildInternal(FotoapparatBuilder.kt:190) 
        at io.fotoapparat.FotoapparatBuilder.build(FotoapparatBuilder.kt:179) 
        at com.fxn.pix.Pix.initialize(Pix.java:373) 
        at com.fxn.pix.Pix.onCreate(Pix.java:325) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2896) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6694) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/fr.geev.application.stage-6HPvTyE1B-ID2YGg3dlnZw==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
2019-02-07 17:20:32.946 28475-28475/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5761)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653)
        		... 6 more
```

**Comment by syahrulhajji** [comment]
You must to upgrade library  implementation  'com.fxn769:pix:1.3.1' but this using material design androidx, and you must migration your project to androidx.
