### ISSUE TITLE
Not able to include library into my project

### ISSUE THREAD

**Issue by athmapatilgs** [akshay2211/PixImagePicker#68]
I am getting some issues while importing the library to my project. 
In gradle.properties  I have included  below 2 lines

android.enableJetifier=true
android.useAndroidX=true

Problem: Because of the android.enableJetifier=true  other SDK is not working and in error it showing

**

> Caused by: java.lang.RuntimeException: Failed to transform 'kSDK1.4.0.jar' using Jetifier. Reason: 6. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.

**
	at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:204)
	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:44)
	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:29)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:224)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:211)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:111)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:107)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:160)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:107)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:50)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:143)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:122)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:89)
	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:193)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:158)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:187)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:122)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:115)
	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.loadIntoCache(DefaultTransformedFileCache.java:115)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.getResult(DefaultTransformedFileCache.java:107)
	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:87)
	
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readFrameType(ClassReader.java:2310)
	at org.objectweb.asm.ClassReader.readFrame(ClassReader.java:2269)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1448)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.android.tools.build.jetifier.processor.transform.bytecode.ByteCodeTransformer.runTransform(ByteCodeTransformer.kt:39)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:328)
	at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:41)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:316)
	at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:66)
	at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:312)
	at com.android.tools.build.jetifier.processor.Processor.transform(Processor.kt:175)
	at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:199)
	... 41 more

**Comment by akshay2211** [comment]
@athmapatilgs 
Pix has been migrated to androidx.
you can use it now.

**Comment by Kevin1466** [comment]
> I am getting some issues while importing the library to my project.
> In gradle.properties I have included below 2 lines
> 
> android.enableJetifier=true
> android.useAndroidX=true
> 
> Problem: Because of the android.enableJetifier=true other SDK is not working and in error it showing
> 
> **
> 
> > Caused by: java.lang.RuntimeException: Failed to transform 'kSDK1.4.0.jar' using Jetifier. Reason: 6. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.
> 
> **
> at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:204)
> at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:44)
> at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:29)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:224)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:211)
> at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:111)
> at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:107)
> at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:160)
> at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:107)
> at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:50)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:143)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:122)
> at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:89)
> at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:193)
> at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:158)
> at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:187)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:122)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:115)
> at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.loadIntoCache(DefaultTransformedFileCache.java:115)
> at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.getResult(DefaultTransformedFileCache.java:107)
> at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:87)
> 
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
> at org.objectweb.asm.ClassReader.readFrameType(ClassReader.java:2310)
> at org.objectweb.asm.ClassReader.readFrame(ClassReader.java:2269)
> at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1448)
> at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
> at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
> at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
> at com.android.tools.build.jetifier.processor.transform.bytecode.ByteCodeTransformer.runTransform(ByteCodeTransformer.kt:39)
> at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:328)
> at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:41)
> at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:316)
> at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:66)
> at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:312)
> at com.android.tools.build.jetifier.processor.Processor.transform(Processor.kt:175)
> at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:199)
> ... 41 more

I met a similar problem in other project. It says, 
"Execution failed for task ':im-sdk:javaPreCompileDebug'.
> Could not resolve all files for configuration ':im-sdk:debugCompileClasspath'.
   > Failed to transform file 'HwPush_SDK_V2705.jar' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}"

How did you tackle with the problem?
