### ISSUE TITLE
IndexOutOfBoundsException MainImageAdapter

### ISSUE THREAD

**Issue by 73k05** [akshay2211/PixImagePicker#79]
Hi,

thank you @akshay2211 for the work you have been doing here :-)

I've got a new crash from the community.

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 393, Size: 104
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.fxn.adapters.MainImageAdapter.getItemViewType(MainImageAdapter.java:72)
       at com.fxn.adapters.MainImageAdapter.isHeader(MainImageAdapter.java:150)
       at com.fxn.adapters.MainImageAdapter.getHeaderPositionForItem(MainImageAdapter.java:128)
       at com.fxn.utility.HeaderItemDecoration.getHeaderViewForItem(HeaderItemDecoration.java:63)
       at com.fxn.utility.HeaderItemDecoration.onDrawOver(HeaderItemDecoration.java:41)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4289)
       at android.view.View.updateDisplayListIfDirty(View.java:19082)
       at android.view.View.draw(View.java:19935)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19073)
       at android.view.View.draw(View.java:19935)
```
I believe the correct line is l75 in the code:
```
    @Override
    public int getItemViewType(int position) {
        ==> Img i = list.get(position); <==
        return (i.getContentUrl().equalsIgnoreCase("")) ?
                HEADER : ITEM;
    }
```

I didn't reproduce it myself yet. Let me know if I can help. I would say the bug appears when the view is not synchronized anymore (maybe a backpress or else). We could add a test like this to avoid crashing:
```
       if(list.length <= position){return 0;}
```

![Screen Shot 2019-05-27 at 7 09 53 AM](https://user-images.githubusercontent.com/9129812/58396830-92310000-804e-11e9-9c51-76cfd1d3d271.png)

Regards
-73k05-

**Comment by Qism0** [comment]
@akshay2211 got similar crash again, want me to make new PR to solve it?
![Screen Shot 2019-09-07 at 2 31 51 PM](https://user-images.githubusercontent.com/9129812/64474965-6dcfde00-d17c-11e9-92a2-f1915270c5f6.png)
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsExceptionlength=10; index=-1 Raw Text
--
  | java.util.ArrayList.get + 439 (ArrayList.java:439)
  | com.fxn.adapters.MainImageAdapter.getSectionMonthYearText + 165 (MainImageAdapter.java:165)
  | com.fxn.pix.Pix.setRecyclerViewPosition + 799 (Pix.java:799)
  | com.fxn.pix.Pix.onTouch + 880 (Pix.java:880)
  | android.view.View.dispatchTouchEvent + 12509 (View.java:12509)
  | com.android.internal.os.ZygoteInit.main + 858 (ZygoteInit.java:858)
```

**Comment by akshay2211** [comment]
Thanks @Qism0 i have added the code [here](https://github.com/akshay2211/PixImagePicker/commit/c9cdd00c566338157b51482ebaf929e90b8db5b0) as you suggested.
will deploy it in some time.
