### ISSUE TITLE
Get an issue on clicking or selecting more than 2 images

### ISSUE THREAD

**Issue by DevToDipesh** [akshay2211/PixImagePicker#84]
Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1687)
        at android.app.Activity.startActivityForResult(Activity.java:4477)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:4435)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at com.fxn.pix.Pix$7.onWorkFinish(Pix.java:313)
        at com.fxn.utility.PermUtil.checkForCamaraWritePermissions(PermUtil.java:68)
        at com.fxn.pix.Pix.start(Pix.java:308)

**Comment by akshay2211** [comment]
Hello @DevToDipesh 
Thanks for tying out [PixImagePicker](https://github.com/akshay2211/PixImagePicker)
can you provide more info on crash.

**Comment by akshay2211** [comment]
because of no response i am closing this issue, feel free to reopen when any such case arise.
